// DO NOT EDIT, CODE GENERATED BY entc. yiziluoying

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GithubEvent is the predicate function for githubevent builders.
type GithubEvent func(*sql.Selector)

// GithubRepository is the predicate function for githubrepository builders.
type GithubRepository func(*sql.Selector)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)
