// DO NOT EDIT, CODE GENERATED BY entc. yiziluoying

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Files is the predicate function for files builders.
type Files func(*sql.Selector)

// GithubEvent is the predicate function for githubevent builders.
type GithubEvent func(*sql.Selector)

// GithubRepository is the predicate function for githubrepository builders.
type GithubRepository func(*sql.Selector)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
