// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GithubEvent is the predicate function for githubevent builders.
type GithubEvent func(*sql.Selector)
