//go:build ignore

package main

import (
	"log"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

const header = `// DO NOT EDIT, CODE GENERATED BY entc. yiziluoying`

func checkError(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	egq, err := entgql.NewExtension(
		entgql.WithConfigPath("./src/database/graphql/gqlgen.yml"),
		entgql.WithSchemaGenerator(),
		entgql.WithSchemaPath("./src/database/graphql/graph/schema/ent.graphqls"),
		entgql.WithWhereInputs(true),
	)
	checkError(err)

	err = entc.Generate(
		"./src/database/schema",
		&gen.Config{
			Target:  "./src/ent/",
			Schema:  "aiisx.com/src/database/schema",
			Package: "aiisx.com/src/ent",
			Header:  header,
			Features: []gen.Feature{
				gen.FeaturePrivacy,
				gen.FeatureEntQL,
				gen.FeatureSnapshot,
				gen.FeatureUpsert,
			},
		},
		entc.Extensions(egq),
	)
	checkError(err)
}
