// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"aiisx.com/src/ent/githubevent"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/go-github/v47/github"
)

// GithubEventCreate is the builder for creating a GithubEvent entity.
type GithubEventCreate struct {
	config
	mutation *GithubEventMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (gec *GithubEventCreate) SetEventID(s string) *GithubEventCreate {
	gec.mutation.SetEventID(s)
	return gec
}

// SetEventType sets the "event_type" field.
func (gec *GithubEventCreate) SetEventType(s string) *GithubEventCreate {
	gec.mutation.SetEventType(s)
	return gec
}

// SetCreatedAt sets the "created_at" field.
func (gec *GithubEventCreate) SetCreatedAt(t time.Time) *GithubEventCreate {
	gec.mutation.SetCreatedAt(t)
	return gec
}

// SetPublic sets the "public" field.
func (gec *GithubEventCreate) SetPublic(b bool) *GithubEventCreate {
	gec.mutation.SetPublic(b)
	return gec
}

// SetNillablePublic sets the "public" field if the given value is not nil.
func (gec *GithubEventCreate) SetNillablePublic(b *bool) *GithubEventCreate {
	if b != nil {
		gec.SetPublic(*b)
	}
	return gec
}

// SetActorID sets the "actor_id" field.
func (gec *GithubEventCreate) SetActorID(i int64) *GithubEventCreate {
	gec.mutation.SetActorID(i)
	return gec
}

// SetActor sets the "actor" field.
func (gec *GithubEventCreate) SetActor(gi *github.User) *GithubEventCreate {
	gec.mutation.SetActor(gi)
	return gec
}

// SetRepoID sets the "repo_id" field.
func (gec *GithubEventCreate) SetRepoID(i int64) *GithubEventCreate {
	gec.mutation.SetRepoID(i)
	return gec
}

// SetRepo sets the "repo" field.
func (gec *GithubEventCreate) SetRepo(gi *github.Repository) *GithubEventCreate {
	gec.mutation.SetRepo(gi)
	return gec
}

// SetPayload sets the "payload" field.
func (gec *GithubEventCreate) SetPayload(m map[string]interface{}) *GithubEventCreate {
	gec.mutation.SetPayload(m)
	return gec
}

// Mutation returns the GithubEventMutation object of the builder.
func (gec *GithubEventCreate) Mutation() *GithubEventMutation {
	return gec.mutation
}

// Save creates the GithubEvent in the database.
func (gec *GithubEventCreate) Save(ctx context.Context) (*GithubEvent, error) {
	var (
		err  error
		node *GithubEvent
	)
	gec.defaults()
	if len(gec.hooks) == 0 {
		if err = gec.check(); err != nil {
			return nil, err
		}
		node, err = gec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GithubEventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gec.check(); err != nil {
				return nil, err
			}
			gec.mutation = mutation
			if node, err = gec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(gec.hooks) - 1; i >= 0; i-- {
			if gec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gec.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, gec.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*GithubEvent)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from GithubEventMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gec *GithubEventCreate) SaveX(ctx context.Context) *GithubEvent {
	v, err := gec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gec *GithubEventCreate) Exec(ctx context.Context) error {
	_, err := gec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gec *GithubEventCreate) ExecX(ctx context.Context) {
	if err := gec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gec *GithubEventCreate) defaults() {
	if _, ok := gec.mutation.Public(); !ok {
		v := githubevent.DefaultPublic
		gec.mutation.SetPublic(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gec *GithubEventCreate) check() error {
	if _, ok := gec.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "GithubEvent.event_id"`)}
	}
	if _, ok := gec.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "GithubEvent.event_type"`)}
	}
	if v, ok := gec.mutation.EventType(); ok {
		if err := githubevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "GithubEvent.event_type": %w`, err)}
		}
	}
	if _, ok := gec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GithubEvent.created_at"`)}
	}
	if _, ok := gec.mutation.Public(); !ok {
		return &ValidationError{Name: "public", err: errors.New(`ent: missing required field "GithubEvent.public"`)}
	}
	if _, ok := gec.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "GithubEvent.actor_id"`)}
	}
	if _, ok := gec.mutation.Actor(); !ok {
		return &ValidationError{Name: "actor", err: errors.New(`ent: missing required field "GithubEvent.actor"`)}
	}
	if _, ok := gec.mutation.RepoID(); !ok {
		return &ValidationError{Name: "repo_id", err: errors.New(`ent: missing required field "GithubEvent.repo_id"`)}
	}
	if v, ok := gec.mutation.RepoID(); ok {
		if err := githubevent.RepoIDValidator(v); err != nil {
			return &ValidationError{Name: "repo_id", err: fmt.Errorf(`ent: validator failed for field "GithubEvent.repo_id": %w`, err)}
		}
	}
	if _, ok := gec.mutation.Repo(); !ok {
		return &ValidationError{Name: "repo", err: errors.New(`ent: missing required field "GithubEvent.repo"`)}
	}
	if _, ok := gec.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "GithubEvent.payload"`)}
	}
	return nil
}

func (gec *GithubEventCreate) sqlSave(ctx context.Context) (*GithubEvent, error) {
	_node, _spec := gec.createSpec()
	if err := sqlgraph.CreateNode(ctx, gec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (gec *GithubEventCreate) createSpec() (*GithubEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &GithubEvent{config: gec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: githubevent.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: githubevent.FieldID,
			},
		}
	)
	if value, ok := gec.mutation.EventID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: githubevent.FieldEventID,
		})
		_node.EventID = value
	}
	if value, ok := gec.mutation.EventType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: githubevent.FieldEventType,
		})
		_node.EventType = value
	}
	if value, ok := gec.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: githubevent.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := gec.mutation.Public(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: githubevent.FieldPublic,
		})
		_node.Public = value
	}
	if value, ok := gec.mutation.ActorID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: githubevent.FieldActorID,
		})
		_node.ActorID = value
	}
	if value, ok := gec.mutation.Actor(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: githubevent.FieldActor,
		})
		_node.Actor = value
	}
	if value, ok := gec.mutation.RepoID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: githubevent.FieldRepoID,
		})
		_node.RepoID = value
	}
	if value, ok := gec.mutation.Repo(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: githubevent.FieldRepo,
		})
		_node.Repo = value
	}
	if value, ok := gec.mutation.Payload(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: githubevent.FieldPayload,
		})
		_node.Payload = value
	}
	return _node, _spec
}

// GithubEventCreateBulk is the builder for creating many GithubEvent entities in bulk.
type GithubEventCreateBulk struct {
	config
	builders []*GithubEventCreate
}

// Save creates the GithubEvent entities in the database.
func (gecb *GithubEventCreateBulk) Save(ctx context.Context) ([]*GithubEvent, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gecb.builders))
	nodes := make([]*GithubEvent, len(gecb.builders))
	mutators := make([]Mutator, len(gecb.builders))
	for i := range gecb.builders {
		func(i int, root context.Context) {
			builder := gecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GithubEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gecb *GithubEventCreateBulk) SaveX(ctx context.Context) []*GithubEvent {
	v, err := gecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gecb *GithubEventCreateBulk) Exec(ctx context.Context) error {
	_, err := gecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gecb *GithubEventCreateBulk) ExecX(ctx context.Context) {
	if err := gecb.Exec(ctx); err != nil {
		panic(err)
	}
}
