// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aiisx.com/src/ent/githubevent"
	"aiisx.com/src/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	githubeventFields := schema.GithubEvent{}.Fields()
	_ = githubeventFields
	// githubeventDescEventType is the schema descriptor for event_type field.
	githubeventDescEventType := githubeventFields[1].Descriptor()
	// githubevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	githubevent.EventTypeValidator = githubeventDescEventType.Validators[0].(func(string) error)
	// githubeventDescPublic is the schema descriptor for public field.
	githubeventDescPublic := githubeventFields[3].Descriptor()
	// githubevent.DefaultPublic holds the default value on creation for the public field.
	githubevent.DefaultPublic = githubeventDescPublic.Default.(bool)
	// githubeventDescRepoID is the schema descriptor for repo_id field.
	githubeventDescRepoID := githubeventFields[6].Descriptor()
	// githubevent.RepoIDValidator is a validator for the "repo_id" field. It is called by the builders before save.
	githubevent.RepoIDValidator = githubeventDescRepoID.Validators[0].(func(int64) error)
}
