mutation createLabel($input: CreateLabelInput!) {
  createLabel(input: $input) {
    id
    name
  }
}

mutation createPost($input: CreatePostInput!) {
    createPost(input: $input) {
        id
    }
}
