query base {
  self {
    id
    name
    login
    avatarURL
  }

  githubUser {
    login
    name
    avatarURL
    bio
    email
    location
    htmlurl
  }
  version {
    commit
    goVersion
    date
  }

  codingStats {
    totalDuration
    totalSeconds
    calculatedDays

    languages {
      language
      totalSeconds
    }
  }
}

query getEvents(
  $count: Int = 25
  $cursor: Cursor = null
  $order: OrderDirection = DESC
  $orderBy: GithubEventOrderField = CREATED_AT
) {
  githubevents(
    first: $count
    after: $cursor
    orderBy: { direction: $order, field: $orderBy }
  ) {
    edges {
      node {
        id
        eventType
        createdAt
        actor {
          login
          avatarURL
        }
        repo {
          name
        }
        payload
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
